### ISSUE TITLE
fca52c23-fc7e-4458-ab5b-4d859459d57b

### ISSUE THREAD

**Issue by RTI-Jackson** [microsoft/vscode-copilot-release#1893]
Type: <b>Bug</b>

To address your concerns:

1. **Viewing Generated Documentation on GitHub**:
   - By default, the generated documentation will be stored in your repository (e.g., in a [`docs`](command:_github.copilot.openSymbolFromReferences?%5B%22%22%2C%5B%7B%22uri%22%3A%7B%22scheme%22%3A%22file%22%2C%22authority%22%3A%22%22%2C%22path%22%3A%22%2Fc%3A%2FUsers%2FJackson%2FDocuments%2FVSCode%2FRTI-Root%2FDispatch_Console%2F.github%2Fworkflows%2Fgenerate-docs.yml%22%2C%22query%22%3A%22%22%2C%22fragment%22%3A%22%22%7D%2C%22pos%22%3A%7B%22line%22%3A34%2C%22character%22%3A19%7D%7D%2C%7B%22uri%22%3A%7B%22scheme%22%3A%22file%22%2C%22authority%22%3A%22%22%2C%22path%22%3A%22%2Fc%3A%2FUsers%2FJackson%2FDocuments%2FVSCode%2FRTI-Root%2FDispatch_Console%2Fpackage.json%22%2C%22query%22%3A%22%22%2C%22fragment%22%3A%22%22%7D%2C%22pos%22%3A%7B%22line%22%3A11%2C%22character%22%3A5%7D%7D%5D%2C%22fca52c23-fc7e-4458-ab5b-4d859459d57b%22%5D "Go to definition") directory). However, it won't be directly viewable on GitHub unless you push the generated files back to the repository or use GitHub Pages to serve the documentation.
   - To push the generated documentation back to the repository, you can add a step in your GitHub Action to commit and push the [`docs`](command:_github.copilot.openSymbolFromReferences?%5B%22%22%2C%5B%7B%22uri%22%3A%7B%22scheme%22%3A%22file%22%2C%22authority%22%3A%22%22%2C%22path%22%3A%22%2Fc%3A%2FUsers%2FJackson%2FDocuments%2FVSCode%2FRTI-Root%2FDispatch_Console%2F.github%2Fworkflows%2Fgenerate-docs.yml%22%2C%22query%22%3A%22%22%2C%22fragment%22%3A%22%22%7D%2C%22pos%22%3A%7B%22line%22%3A34%2C%22character%22%3A19%7D%7D%2C%7B%22uri%22%3A%7B%22scheme%22%3A%22file%22%2C%22authority%22%3A%22%22%2C%22path%22%3A%22%2Fc%3A%2FUsers%2FJackson%2FDocuments%2FVSCode%2FRTI-Root%2FDispatch_Console%2Fpackage.json%22%2C%22query%22%3A%22%22%2C%22fragment%22%3A%22%22%7D%2C%22pos%22%3A%7B%22line%22%3A11%2C%22character%22%3A5%7D%7D%5D%2C%22fca52c23-fc7e-4458-ab5b-4d859459d57b%22%5D "Go to definition") directory. Here’s how you can modify your workflow to include this step:

```yaml
name: Generate Documentation and Lint

on:
  push:
    branches:
      - master
      - staging
      - FEAT/*
      - CHORE/*
      - ENHANCEMENT/*
      - FIX/*
      - SECURITY/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Lint changed files
      run: |
        git diff --name-only HEAD^ HEAD | grep '\.js$' | xargs npx eslint

    - name: Generate Documentation
      run: npm run docs

    - name: Commit and Push Documentation
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs
        git commit -m 'Update documentation'
        git push origin HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

2. **Node.js Version Deprecation Warning**:
   - The warning you are seeing is related to the actions themselves running on Node.js 12, which is deprecated. You can update the actions to use the latest versions that run on Node.js 16 or later.
   - Update the actions to the latest versions:

```yaml
name: Generate Documentation and Lint

on:
  push:
    branches:
      - master
      - staging
      - FEAT/*
      - CHORE/*
      - ENname: Generate Documentation and Lint

on:
  push:
    branches:
      - master
      - staging
      - FEAT/*
      - CHORE/*
      - EN

Extension version: 0.21.0
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1360P (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.56GB (14.74GB free)|
|Process Argv|--crash-reporter-id aa419339-02de-4a6a-8c21-f7041149176e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31156133
notype1:31157159
5fd0e150:31155592
iconenabled:31158251

```

</details>

<!-- generated by issue reporter -->
