### ISSUE TITLE
Chat provides duplicated lines

### ISSUE THREAD

**Issue by JoshuaKemmerer** [microsoft/vscode-copilot-release#4264]
Type: <b>Bug</b>

Selected the following serverless framework configuration file text:

```yaml
  private:
    domain: ${env:USER_SUB_DOMAIN, 'localhost'}
```

My prompt:

```
How do I add the text 'auth' to the beginning of `env:USER_SUB_DOMAIN` and not `'localhost'`?
```

the output:

```
To add the text 'auth' to the beginning of the `env:USER_SUB_DOMAIN` environment variable and not to the default value `'localhost'`, you can use the `${env:}` syntax along with the `${self:}` syntax to concatenate strings conditionally.

Here's how you can do it:

### Updated 

serverless.yml

 )

<escaped>```yaml
private:
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
  domain: ${env:USER_SUB_DOMAIN, 'localhost'}
<escaped>```

```

Extension version: 0.23.2
VS Code version: Code 1.96.3 (Universal) (91fbdddc47bc9c09064bf7acf133d22631cbf083, 2025-01-09T18:14:09.060Z)
OS version: Darwin arm64 24.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>
