### ISSUE TITLE
Unable to submit chats

### ISSUE THREAD

**Issue by jmineau** [microsoft/vscode-copilot-release#565]
Hello, I am unable to use VSCode Copilot Chat through the Remote-SSH extension. This might be related to #371, but I wanted to provide more info.

I am on Windows 11 connecting to a remote linux server. Copilot chat had been working fine until a few days ago. I am no longer able to submit any chats. I have tried completely removing the `.vscode-server`, uninstalling & reinstalling Copilot & Copilot Chat, using the Pre-Release version, and using VSCode Insiders. It is not host specific as the same thing happens on other hosts. Chat does work locally though.

I can open the Chat view from the Activity Bar. I can then type in the text box. But when I click submit or hit enter - nothing happens. 

Additionally, the Clear and History buttons in the upper right corner of the Chat view are grayed out.

When I click Send Chat Feedback, a message saying, "Activating Extensions..." shows up in the Status Bar, but otherwise nothing happens.

If I go to Chat extensions view > Runtime Status, I see:
>Not yet activated.

Though the Copilot extension view > Runtime Status says: 
>Activation Event: onStartupFinished
Activation Time: 871ms"

There is literally nothing in the Github Copilot & Github Copilot Chat output.

This is what is in the Github Authentication output:

> 2023-11-12 13:17:29.055 [info] Getting sessions for all scopes...
2023-11-12 13:17:29.056 [info] Got 3 sessions for ...
2023-11-12 13:17:29.230 [info] Getting sessions for read:org,user:email...
2023-11-12 13:17:29.230 [info] Got 1 sessions for read:org,user:email...
2023-11-12 13:17:29.297 [info] Getting sessions for read:org,user:email...
2023-11-12 13:17:29.297 [info] Got 1 sessions for read:org,user:email...
2023-11-12 13:17:31.508 [info] Getting sessions for read:user,repo,user:email,workflow...
2023-11-12 13:17:31.508 [info] Got 0 sessions for read:user,repo,user:email,workflow...
2023-11-12 13:17:31.531 [info] Getting sessions for read:user...
2023-11-12 13:17:31.531 [info] Got 1 sessions for read:user...

Any help would be greatly appreciated.

Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by Wenbobobo** [comment]
i met the same problem after an update days ago. There's nothing in the chat log and the "send" button is grey and can't do anything. Also the Chat extensions 'view > Runtime Status' :Not yet activated and the Copilot extension 'view > Runtime Status' says: Activation Event: onStartupFinished. 
Nothing in the chat log and the copilot log is: 
[DEBUG] [proxy-socket-factory] [2023-11-21T09:00:55.224Z] Attempting to establish connection to proxy
[DEBUG] [proxy-socket-factory] [2023-11-21T09:00:55.226Z] Socket Connect returned status code,200
[DEBUG] [proxy-socket-factory] [2023-11-21T09:00:55.226Z] Successfully established tunneling connection to proxy

VS Code Version: 1.85.0-insider(user setup)
OS Version:Windows 100.19044
GitHub Copilot: v1.138.0
GitHub Copilot Chat: v0.11.2023112001

It's really helpful if there's any solution!

**Comment by Wenbobobo** [comment]
i sucesss when the chat version in **v0.10.0** and copilot in **v1.128.0**. You can have a try.
@jmineau 
the chat log:
2023-11-21T09:23:34.135Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
2023-11-21T09:23:34.135Z [INFO] [chat fetch] modelMaxTokenWindow 8192
2023-11-21T09:23:34.135Z [INFO] [chat fetch] chat model gpt-3.5👀
2023-11-21T09:23:35.414Z [INFO] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1279 ms
2023-11-21T09:23:35.415Z [INFO] [streamMessages] message 0 returned. finish reason: [stop]
2023-11-21T09:23:35.416Z [INFO] [streamChoices] request done: headerRequestId: [05aaa6-30c9-428-a86-1eccff7b0f] model deployment ID: [xba94157a3481]

**Comment by JosephLYH** [comment]
I am also having this problem. I have recently updated the stable version to 1.84.2 and tried to install VS Code insiders to get around the "Please check your firewall rules and network connection then try again. Error Code: ECONNRESET." problem. So tinkering with the insiders version caused both my stable and insiders version to have this bug. Now the start inline chat, and chat tab doesn't work.

**Comment by TylerLeonhardt** [comment]
Sorry for the delay here, I was on vacation and just saw this. Are you still seeing this issue with:
* [Latest VS Code Insiders](https://code.visualstudio.com/insiders)
* Latest Prerelease of [Copilot](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot) (as of today, it's v1.138.570)
* Latest Prerelease of [Copilot Chat](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat) (as of today, it's v0.11.2023112701)

And can you also tell me a little bit about your SSH environment?

**Comment by Shualdon** [comment]
I also have this problem. Both with Copilot and the Chat. 
Can't send anything to the chat - pressing enter or the submit button does nothing.
Can't use copilot's code completion, doc generation, etc. 
When I try to use any of them VS Code shows "Activating Extensions..." for a few seconds but nothing happens. The output window is empty for both extensions.

I have tried to do everything suggested in this thread and nothing works. I even tried to install an older version of the SSH extension, just in case, and that also didn't work. Deleting the `.vscode-server` folder from the remote location also didn't work.
I am also seeing this issue using @TylerLeonhardt's suggestions - the same results with VS Code Insiders with the latest releases of the extensions.
I also tried to disable a bunch of other extensions to see if any of them interfered with Copilot, but that one also didn't work.

I am connected to my org's server with SSH and a VPN. Copilot used to work with this setup before, so I am not sure what changed. I'm using win11 and the server is Linux.

I have tried using Copilot in WSL, and that worked. So it seems like it is something specific with the ssh connection.

If it helps, here's the Diagnostics output:

```yaml
## Copilot

- Version: 1.139.0
- Build: prod
- Editor: vscode/1.84.2

## Environment

- http_proxy: n/a
- https_proxy: n/a
- no_proxy: n/a
- SSL_CERT_FILE: n/a
- SSL_CERT_DIR: n/a
- OPENSSL_CONF: n/a

## Feature Flags

- Custom Certificates: disabled
- Send Restricted Telemetry: enabled
- Chat: enabled

## Node setup

- Number of root certificates: 140
- Operating system: Linux
- Operating system version: 3.10.0-1160.99.1.el7.x86_64
- Operating system architecture: x64
- NODE_OPTIONS: n/a
- NODE_EXTRA_CA_CERTS: n/a
- NODE_TLS_REJECT_UNAUTHORIZED: n/a
- tls default min version: TLSv1.2
- tls default max version: TLSv1.3

## Network Configuration

- Proxy host: n/a
- Proxy port: n/a
- Proxy auth: n/a
- Kerberos SPN: n/a
- Reject unauthorized: disabled

## Reachability

- github.com: HTTP 200 - 
- copilot-proxy.githubusercontent.com: HTTP 200 - 
- default.exp-tas.com: HTTP 200 - 

## VS Code Configuration

- HTTP proxy: 
- HTTP proxy autentication: n/a
- Proxy Strict SSL: true
- Extension HTTP proxy support: override

## Extensions

- Is `win-ca` installed?: false
- Is `mac-ca` installed?: false
```
