### ISSUE TITLE
YAML blank line and file ending formatting issues

### ISSUE THREAD

**Issue by Prefection** [microsoft/vscode-copilot-release#9291]
- Copilot Chat Extension Version: 0.28.2025050901
- VS Code Version: 1.101.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.26100 remote to WSL Ubuntu 22.04
- Logs:

## Summary

When using GitHub Copilot Chat to fix YAML formatting issues (such as removing extra blank lines and ensuring a single newline at the end of a file), Copilot repeatedly failed to:

- Remove blank lines that contain only spaces or tabs.
- Ensure there is only a single newline at the end of the file (i.e., file ends with `\n`, not `\n\n`).
- Remove blank lines between YAML keys/values that should be contiguous.

## Steps to Reproduce

1. Use Copilot Chat to fix YAML lint issues in a file (e.g., `[MASKED_FILENAME].yml`).
2. Request Copilot to:
    - Remove lines that contain only spaces or tabs (should be true blank lines).
    - Ensure the file ends with exactly one newline (not multiple blank lines).
    - Remove blank lines between YAML keys/values that should be together.
3. Observe that Copilot:
    - Sometimes leaves lines with only spaces/tabs.
    - Sometimes leaves more than one newline at the end of the file.
    - Sometimes adds or fails to remove blank lines between YAML keys/values.

## Expected Behavior

- All blank lines should be true blank lines (no spaces or tabs).
- There should be no blank lines between YAML keys/values that should be together.
- The file should end with exactly one newline (not multiple blank lines).

## Actual Behavior

- Copilot left lines with only spaces/tabs.
- Copilot left more than one newline at the end of the file.
- Copilot sometimes added or failed to remove blank lines between YAML keys/values.

## Example

**Input:**
```yaml
    - name: Unarchive a binary file
      ansible.builtin.unarchive:
        src: [MASKED_SRC_PATH]
        dest: [MASKED_DEST_PATH]
        remote_src: true
# 2 blank newlines here
```

**Expected:**
```yaml
    - name: Unarchive a binary file
      ansible.builtin.unarchive:
        src: [MASKED_SRC_PATH]
        dest: [MASKED_DEST_PATH]
        remote_src: true
# just 1 blank newline here
```

**Actual (from Copilot):**
```yaml
    - name: Unarchive a binary file
      ansible.builtin.unarchive:
        src: [MASKED_SRC_PATH]
        dest: [MASKED_DEST_PATH]
# random newline appear here from Copilot patch
        remote_src: true
# still 2 blank newlines here
```

Or, file ends with:
```
remote_src: true\n\n
```
Instead of:
```
remote_src: true\n
```

## Additional Notes
- The problem persisted after multiple patch attempts.
- Manual editing was required to achieve the correct formatting.

---

Please investigate and improve Copilot's handling of blank lines and file endings in YAML and other text files.

**Comment by fdcastel** [comment]
Just dropping in to confirm that I'm experiencing the same issue. 

**Editing YAML files with any model is becoming a nightmare!**

Typically, the model tries multiple edits before eventually giving up and rewriting the entire file from scratch. While that usually works, it wastes a lot of time and consumes unnecessary agent tokens.

I can't pinpoint exactly when this started, but it's definitely been happening for over two weeks.

A simple example: Often when the model wants to do this

```
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Disable shallow fetch (required for GitVersion)
```

The final version of the edited file ends like this:

```
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Disable shallow fetch (required for GitVersion)
```

causing havoc. 

Problem is that **the model isn’t even aware the file is broken** until it tries to run code that fails due to the incorrect file.

I'm happy to provide additional examples or help debug the issue if needed.
