### ISSUE TITLE
Customizable Custom Modes

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-copilot-release#9452]
Allow to add new entries to the modes dropdown that act as "sticky prompt".

- [ ] A mode based on a prompt file: markdown instructions, `model` and `tools`.
- [ ] Add new "model" field (name or id?)
- [ ] Add new "name" field for a nice display name
- [ ] Support "mode" field in prompt files
- [ ] Setting to set default mode
- [ ] Mode-flag in prompt files to assign them to the mode picker.
- [ ] Golden scenarios based on customer input on how modes differ from prompts
   - Roo Code: Ask, Plan, Act, Debug
   - Levers: Secure vs YOLO, Vibe vs Always Confirm, 

Backlog:
- Other idea, new folder/file type: .vscode/modes/automate.mode.md
- New metadata field "alwaysAttach" for must-have context (like plan)
- Later: Automatic mode switching and multi-mode agentic orchestration

**Comment by opentechexpert** [comment]
I see it is already available in VS Code Insiders.

<img width="660" alt="Image" src="https://github.com/user-attachments/assets/17de13fe-4552-4512-9cca-7f4a6f18bd87" />

<img width="657" alt="Image" src="https://github.com/user-attachments/assets/a73617bc-c73d-4a91-97ba-fee0242d161e" />

<img width="1029" alt="Image" src="https://github.com/user-attachments/assets/27699833-06e4-4708-835a-cb070bf010f9" />

Question: How to use it in chat, and what is the relation with instructions and prompt files?

**Comment by opentechexpert** [comment]
Based on the prompt file you've shared, I can help explain this issue for a GitHub issue. Here's an explanation of the problem:

Issue: Chat Mode Tool Access Inconsistency
Both [Dev.chatmode.md] and [dev.task.create-astro-comp.prompt.md] configurations specify access to the editFiles tool in their respective tool arrays:

In the task prompt [dev.task.create-astro-comp.prompt.md]:

Expected behavior: Both modes should have the ability to edit files since they both explicitly list editFiles in their tools configuration.

Actual behavior: When using Dev chat mode, the system indicates it cannot edit files, despite the editFiles tool being listed in the configuration.

Problem: There appears to be a discrepancy between:

The declared tool permissions in the configuration files
The actual runtime tool access is granted to the chat mode when executing the prompt file
This suggests either:

The editFiles tool permission is not being properly inherited or applied in chat mode
There's a difference in how tool permissions are processed in custom chat mode.
The chat mode has additional restrictions that override the declared tool permissions
Expected Resolution: Chat mode should respect the tool permissions declared in its configuration and allow file editing operations when "editFiles" is explicitly listed in the tools array.

The prompt works as expected in Agent mode.

/workspaces/prd/.github/chatmodes/Dev.chatmode.md

````
---
description: 'Developer: A custom chat mode for developers to interact with code, run commands, and manage tools.'
tools: ['codebase', 'terminalSelection', 'terminalLastCommand', 'findTestFiles', 'editFiles', 'runCommands', 'search']
---
# Developer Chat Mode
The Developer chat mode is designed to assist developers in interacting with code, running commands, and managing tools. It provides a comprehensive set of features to streamline development workflows and enhance productivity.
## Features
- **Codebase Access**: Retrieve and browse codebase information to understand the context of development tasks.
- **Command Execution**: Run commands directly from the chat interface to perform various development tasks.
- **Problem Management**: View and manage problems in the codebase to identify issues that need fixing.
- **File Editing**: Make changes to files directly from the chat interface, with real-time feedback.
- **GitHub Integration**: Access GitHub repositories to manage issues, pull requests, and other resources.

````

.github/prompts/dev.task.create-astro-comp.prompt.md

````
---
mode: 'agent'
tools: ['codebase', 'terminalSelection', 'terminalLastCommand', 'findTestFiles', 'editFiles', 'runCommands', 'search']
---
Create a astro component named ${input:variableName:myComponent} in the current directory. The component should include a simple template that displays a message "Hello, Astro!" and a script that logs "Component loaded" to the console.

directory: /src/components/${input:variableName:myComponent}.astro

```astro
---
// ${input:variableName:myComponent}.astro
---
<h1>Hello, Astro!</h1>
<script>
  console.log("Component loaded");
</script>
````


GitHub Copilot chat answer

````

GitHub Copilot: I'll create an Astro component named `hello.astro` for you. Let me first check the current workspace structure to understand the project layout better. I can see this workspace doesn't have an existing Astro project structure. Let me create the `hello.astro` component following the pattern from the prompt template. Based on the template, I'll create the component in a `src/components` directory structure.

Since I can't edit files directly, I'll provide you with the code structure and suggest creating the necessary directories:

## Directory Structure Needed

First, you'll need to create the directory structure:

```bash
mkdir -p src/components
```

## Astro Component Code

Here's the `hello.astro` component code to create in `/src/components/hello.astro`:

```astro
---
// hello.astro
---
<h1>Hello, Astro!</h1>
<script>
  console.log("Component loaded");
</script>
```

This Astro component includes:

1. **Frontmatter section** (between the `---` markers) - This is where you'd typically put component logic, imports, or props
2. **Template section** - Contains the HTML that displays "Hello, Astro!" 
3. **Script section** - Logs "Component loaded" to the browser console when the component is loaded

## Usage

Once created, you can use this component in other Astro pages or components by importing it:

```astro
---
import Hello from '../components/hello.astro';
---

<Hello />
```

Would you like me to help you set up a complete Astro project structure, or do you need assistance with anything else related to this component?
````

**Comment by opentechexpert** [comment]
Suggestion to filter the prompt by a custom agent

<img width="1436" alt="Image" src="https://github.com/user-attachments/assets/45926709-7227-4304-8818-acae892d092d" />

```
---
mode: 'Agent | Ask | Edit' // Set custom agent mode
description: 'Developer: A custom chat mode for developers to interact with code, run commands, and manage tools.'
tools: ['codebase', 'terminalSelection', 'terminalLastCommand', 'findTestFiles', 'editFiles', 'runCommands', 'search']
// Suggested to filter on input chat mode
prompts: 
  - folder: prompts/dev //Index of prompts for the Developer chat mode
  - file: prompts/dev.task.**.prompt.md // All prompts related to tasks in the Developer chat mode
---
# Developer Chat Mode
The Developer chat mode is designed to assist developers in interacting with code, running commands, and managing tools. It provides a comprehensive set of features to streamline development workflows and enhance productivity.
## Features
- **Codebase Access**: Retrieve and browse codebase information to understand the context of development tasks.
- **Command Execution**: Run commands directly from the chat interface to perform various development tasks.
- **Problem Management**: View and manage problems in the codebase to identify issues that need fixing.
- **File Editing**: Make changes to files directly from the chat interface, with real-time feedback.
- **GitHub Integration**: Access GitHub repositories to manage issues, pull requests, and other resources.
```
